POST https://crispy-xylophone-4xqwvjj7r46c7gvq-8000.app.github.dev/train

###

GET https://crispy-xylophone-4xqwvjj7r46c7gvq-8000.app.github.dev/predict/left/1/right/1

###

GET https://crispy-xylophone-4xqwvjj7r46c7gvq-8000.app.github.dev/predict/left/0/right/0

###

POST https://crispy-xylophone-4xqwvjj7r46c7gvq-8000.app.github.dev/generate
Content-Type: application/json

{
    "prompt": "Tell me about Sam Altman",
    "max_length": 100
}

###
GET https://crispy-xylophone-4xqwvjj7r46c7gvq-8000.app.github.dev/chat?user=musun choi&text=My name is musun choi

###
GET https://crispy-xylophone-4xqwvjj7r46c7gvq-8000.app.github.dev/search?user=musun choi&text=what is the whether in Seoul?

###
GET https://crispy-xylophone-4xqwvjj7r46c7gvq-8000.app.github.dev/research?user=choi musun&text=What is Task Decomposition?